baseURL: "http://aidenomondi.netlify.app" # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: Aiden Omondi
paginate: 5
theme: papermod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

minify:
    disableXML: true
    # minifyOutput: true

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    profileMode:
        enabled: true
        title: "Aiden Omondi" # optional default will be site title
        subtitle: "Programmer"
        imageUrl: "/aidenomondi.jpg" # optional
        imageTitle: "<title of image as alt>" # optional
        imageWidth: 256 # custom size
        imageHeight: 256 # custom size
        buttons:
            - name: Archive
              url: "/archives/"
            - name: Github
              url: "https://github.com/Tech-Helper503/personal-site"
            - name: My Posts
              url: "/posts/"

    socialIcons: # optional
        - name: "YouTube"
          url: "https://youtube.com/@codingperks"
        - name: "Github"
          url: "https://github.com/Tech-Helper503"